// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/subscribe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_api_proto_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_api_proto_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteSubscriptionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeleteSubscriptionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeleteSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_api_proto_subscribe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_subscribe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{3}
}

type SubscriptionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Repository          `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsList) Reset() {
	*x = SubscriptionsList{}
	mi := &file_api_proto_subscribe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsList) ProtoMessage() {}

func (x *SubscriptionsList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsList.ProtoReflect.Descriptor instead.
func (*SubscriptionsList) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriptionsList) GetSubscriptions() []*Repository {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_api_proto_subscribe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{5}
}

func (x *Repository) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CheckRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRepoRequest) Reset() {
	*x = CheckRepoRequest{}
	mi := &file_api_proto_subscribe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRepoRequest) ProtoMessage() {}

func (x *CheckRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRepoRequest.ProtoReflect.Descriptor instead.
func (*CheckRepoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{6}
}

func (x *CheckRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CheckRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type CheckRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRepoResponse) Reset() {
	*x = CheckRepoResponse{}
	mi := &file_api_proto_subscribe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRepoResponse) ProtoMessage() {}

func (x *CheckRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRepoResponse.ProtoReflect.Descriptor instead.
func (*CheckRepoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_proto_rawDescGZIP(), []int{7}
}

func (x *CheckRepoResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_api_proto_subscribe_proto protoreflect.FileDescriptor

const file_api_proto_subscribe_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/subscribe.proto\x12\tsubscribe\"^\n" +
	"\x19CreateSubscriptionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"^\n" +
	"\x19DeleteSubscriptionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"J\n" +
	"\x14SubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"P\n" +
	"\x11SubscriptionsList\x12;\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x15.subscribe.RepositoryR\rsubscriptions\"6\n" +
	"\n" +
	"Repository\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"<\n" +
	"\x10CheckRepoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"+\n" +
	"\x11CheckRepoResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xd5\x02\n" +
	"\x10SubscribeService\x12[\n" +
	"\x12CreateSubscription\x12$.subscribe.CreateSubscriptionRequest\x1a\x1f.subscribe.SubscriptionResponse\x12L\n" +
	"\x12DeleteSubscription\x12$.subscribe.DeleteSubscriptionRequest\x1a\x10.subscribe.Empty\x12B\n" +
	"\x10GetSubscriptions\x12\x10.subscribe.Empty\x1a\x1c.subscribe.SubscriptionsList\x12R\n" +
	"\x15CheckRepositoryExists\x12\x1b.subscribe.CheckRepoRequest\x1a\x1c.subscribe.CheckRepoResponseBFZDgithub.com/LuhTonkaYeat/GoHomeworks/hw2/services/subscribe/api/protob\x06proto3"

var (
	file_api_proto_subscribe_proto_rawDescOnce sync.Once
	file_api_proto_subscribe_proto_rawDescData []byte
)

func file_api_proto_subscribe_proto_rawDescGZIP() []byte {
	file_api_proto_subscribe_proto_rawDescOnce.Do(func() {
		file_api_proto_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscribe_proto_rawDesc), len(file_api_proto_subscribe_proto_rawDesc)))
	})
	return file_api_proto_subscribe_proto_rawDescData
}

var file_api_proto_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_subscribe_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil), // 0: subscribe.CreateSubscriptionRequest
	(*DeleteSubscriptionRequest)(nil), // 1: subscribe.DeleteSubscriptionRequest
	(*SubscriptionResponse)(nil),      // 2: subscribe.SubscriptionResponse
	(*Empty)(nil),                     // 3: subscribe.Empty
	(*SubscriptionsList)(nil),         // 4: subscribe.SubscriptionsList
	(*Repository)(nil),                // 5: subscribe.Repository
	(*CheckRepoRequest)(nil),          // 6: subscribe.CheckRepoRequest
	(*CheckRepoResponse)(nil),         // 7: subscribe.CheckRepoResponse
}
var file_api_proto_subscribe_proto_depIdxs = []int32{
	5, // 0: subscribe.SubscriptionsList.subscriptions:type_name -> subscribe.Repository
	0, // 1: subscribe.SubscribeService.CreateSubscription:input_type -> subscribe.CreateSubscriptionRequest
	1, // 2: subscribe.SubscribeService.DeleteSubscription:input_type -> subscribe.DeleteSubscriptionRequest
	3, // 3: subscribe.SubscribeService.GetSubscriptions:input_type -> subscribe.Empty
	6, // 4: subscribe.SubscribeService.CheckRepositoryExists:input_type -> subscribe.CheckRepoRequest
	2, // 5: subscribe.SubscribeService.CreateSubscription:output_type -> subscribe.SubscriptionResponse
	3, // 6: subscribe.SubscribeService.DeleteSubscription:output_type -> subscribe.Empty
	4, // 7: subscribe.SubscribeService.GetSubscriptions:output_type -> subscribe.SubscriptionsList
	7, // 8: subscribe.SubscribeService.CheckRepositoryExists:output_type -> subscribe.CheckRepoResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_subscribe_proto_init() }
func file_api_proto_subscribe_proto_init() {
	if File_api_proto_subscribe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscribe_proto_rawDesc), len(file_api_proto_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscribe_proto_goTypes,
		DependencyIndexes: file_api_proto_subscribe_proto_depIdxs,
		MessageInfos:      file_api_proto_subscribe_proto_msgTypes,
	}.Build()
	File_api_proto_subscribe_proto = out.File
	file_api_proto_subscribe_proto_goTypes = nil
	file_api_proto_subscribe_proto_depIdxs = nil
}
