// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/collector/collector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorRepoRequest) Reset() {
	*x = CollectorRepoRequest{}
	mi := &file_api_proto_collector_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorRepoRequest) ProtoMessage() {}

func (x *CollectorRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorRepoRequest.ProtoReflect.Descriptor instead.
func (*CollectorRepoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_collector_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CollectorRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type CollectorRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Stars         int32                  `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
	Forks         int32                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorRepoResponse) Reset() {
	*x = CollectorRepoResponse{}
	mi := &file_api_proto_collector_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorRepoResponse) ProtoMessage() {}

func (x *CollectorRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorRepoResponse.ProtoReflect.Descriptor instead.
func (*CollectorRepoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *CollectorRepoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectorRepoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CollectorRepoResponse) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *CollectorRepoResponse) GetForks() int32 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *CollectorRepoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_collector_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_collector_proto_rawDescGZIP(), []int{2}
}

type SubscriptionsInfoResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Repositories  []*CollectorRepoResponse `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsInfoResponse) Reset() {
	*x = SubscriptionsInfoResponse{}
	mi := &file_api_proto_collector_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsInfoResponse) ProtoMessage() {}

func (x *SubscriptionsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsInfoResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionsInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_collector_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionsInfoResponse) GetRepositories() []*CollectorRepoResponse {
	if x != nil {
		return x.Repositories
	}
	return nil
}

var File_api_proto_collector_collector_proto protoreflect.FileDescriptor

const file_api_proto_collector_collector_proto_rawDesc = "" +
	"\n" +
	"#api/proto/collector/collector.proto\x12\tcollector\"@\n" +
	"\x14CollectorRepoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\x98\x01\n" +
	"\x15CollectorRepoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05stars\x18\x03 \x01(\x05R\x05stars\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x05R\x05forks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\a\n" +
	"\x05Empty\"a\n" +
	"\x19SubscriptionsInfoResponse\x12D\n" +
	"\frepositories\x18\x01 \x03(\v2 .collector.CollectorRepoResponseR\frepositories2\xba\x01\n" +
	"\x10CollectorService\x12T\n" +
	"\rGetRepository\x12\x1f.collector.CollectorRepoRequest\x1a .collector.CollectorRepoResponse\"\x00\x12P\n" +
	"\x14GetSubscriptionsInfo\x12\x10.collector.Empty\x1a$.collector.SubscriptionsInfoResponse\"\x00BHZFgithub.com/LuhTonkaYeat/GoHomeworks/hw2-4/services/collector/api/protob\x06proto3"

var (
	file_api_proto_collector_collector_proto_rawDescOnce sync.Once
	file_api_proto_collector_collector_proto_rawDescData []byte
)

func file_api_proto_collector_collector_proto_rawDescGZIP() []byte {
	file_api_proto_collector_collector_proto_rawDescOnce.Do(func() {
		file_api_proto_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_collector_collector_proto_rawDesc), len(file_api_proto_collector_collector_proto_rawDesc)))
	})
	return file_api_proto_collector_collector_proto_rawDescData
}

var file_api_proto_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_collector_collector_proto_goTypes = []any{
	(*CollectorRepoRequest)(nil),      // 0: collector.CollectorRepoRequest
	(*CollectorRepoResponse)(nil),     // 1: collector.CollectorRepoResponse
	(*Empty)(nil),                     // 2: collector.Empty
	(*SubscriptionsInfoResponse)(nil), // 3: collector.SubscriptionsInfoResponse
}
var file_api_proto_collector_collector_proto_depIdxs = []int32{
	1, // 0: collector.SubscriptionsInfoResponse.repositories:type_name -> collector.CollectorRepoResponse
	0, // 1: collector.CollectorService.GetRepository:input_type -> collector.CollectorRepoRequest
	2, // 2: collector.CollectorService.GetSubscriptionsInfo:input_type -> collector.Empty
	1, // 3: collector.CollectorService.GetRepository:output_type -> collector.CollectorRepoResponse
	3, // 4: collector.CollectorService.GetSubscriptionsInfo:output_type -> collector.SubscriptionsInfoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_collector_collector_proto_init() }
func file_api_proto_collector_collector_proto_init() {
	if File_api_proto_collector_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_collector_collector_proto_rawDesc), len(file_api_proto_collector_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_collector_collector_proto_goTypes,
		DependencyIndexes: file_api_proto_collector_collector_proto_depIdxs,
		MessageInfos:      file_api_proto_collector_collector_proto_msgTypes,
	}.Build()
	File_api_proto_collector_collector_proto = out.File
	file_api_proto_collector_collector_proto_goTypes = nil
	file_api_proto_collector_collector_proto_depIdxs = nil
}
