// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/subscribe/subscribe.proto

package subscribe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_subscribe_subscribe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_subscribe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{0}
}

type SubscriptionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Repository          `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsList) Reset() {
	*x = SubscriptionsList{}
	mi := &file_api_proto_subscribe_subscribe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsList) ProtoMessage() {}

func (x *SubscriptionsList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_subscribe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsList.ProtoReflect.Descriptor instead.
func (*SubscriptionsList) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionsList) GetSubscriptions() []*Repository {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_api_proto_subscribe_subscribe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscribe_subscribe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_api_proto_subscribe_subscribe_proto_rawDescGZIP(), []int{2}
}

func (x *Repository) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_proto_subscribe_subscribe_proto protoreflect.FileDescriptor

const file_api_proto_subscribe_subscribe_proto_rawDesc = "" +
	"\n" +
	"#api/proto/subscribe/subscribe.proto\x12\tsubscribe\"\a\n" +
	"\x05Empty\"P\n" +
	"\x11SubscriptionsList\x12;\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x15.subscribe.RepositoryR\rsubscriptions\"6\n" +
	"\n" +
	"Repository\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2X\n" +
	"\x10SubscribeService\x12D\n" +
	"\x10GetSubscriptions\x12\x10.subscribe.Empty\x1a\x1c.subscribe.SubscriptionsList\"\x00BRZPgithub.com/LuhTonkaYeat/GoHomeworks/hw2-4/services/collector/api/proto/subscribeb\x06proto3"

var (
	file_api_proto_subscribe_subscribe_proto_rawDescOnce sync.Once
	file_api_proto_subscribe_subscribe_proto_rawDescData []byte
)

func file_api_proto_subscribe_subscribe_proto_rawDescGZIP() []byte {
	file_api_proto_subscribe_subscribe_proto_rawDescOnce.Do(func() {
		file_api_proto_subscribe_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscribe_subscribe_proto_rawDesc), len(file_api_proto_subscribe_subscribe_proto_rawDesc)))
	})
	return file_api_proto_subscribe_subscribe_proto_rawDescData
}

var file_api_proto_subscribe_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_subscribe_subscribe_proto_goTypes = []any{
	(*Empty)(nil),             // 0: subscribe.Empty
	(*SubscriptionsList)(nil), // 1: subscribe.SubscriptionsList
	(*Repository)(nil),        // 2: subscribe.Repository
}
var file_api_proto_subscribe_subscribe_proto_depIdxs = []int32{
	2, // 0: subscribe.SubscriptionsList.subscriptions:type_name -> subscribe.Repository
	0, // 1: subscribe.SubscribeService.GetSubscriptions:input_type -> subscribe.Empty
	1, // 2: subscribe.SubscribeService.GetSubscriptions:output_type -> subscribe.SubscriptionsList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_subscribe_subscribe_proto_init() }
func file_api_proto_subscribe_subscribe_proto_init() {
	if File_api_proto_subscribe_subscribe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscribe_subscribe_proto_rawDesc), len(file_api_proto_subscribe_subscribe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscribe_subscribe_proto_goTypes,
		DependencyIndexes: file_api_proto_subscribe_subscribe_proto_depIdxs,
		MessageInfos:      file_api_proto_subscribe_subscribe_proto_msgTypes,
	}.Build()
	File_api_proto_subscribe_subscribe_proto = out.File
	file_api_proto_subscribe_subscribe_proto_goTypes = nil
	file_api_proto_subscribe_subscribe_proto_depIdxs = nil
}
