// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID        int32
	UserID    string
	Owner     string
	Repo      string
	CreatedAt pgtype.Timestamp
}
