// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (user_id, owner, repo)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, owner, repo) DO NOTHING
`

type CreateSubscriptionParams struct {
	UserID string
	Owner  string
	Repo   string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription, arg.UserID, arg.Owner, arg.Repo)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE user_id = $1 AND owner = $2 AND repo = $3
`

type DeleteSubscriptionParams struct {
	UserID string
	Owner  string
	Repo   string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.UserID, arg.Owner, arg.Repo)
	return err
}

const getSubscriptions = `-- name: GetSubscriptions :many
SELECT owner, repo FROM subscriptions
WHERE user_id = $1
`

type GetSubscriptionsRow struct {
	Owner string
	Repo  string
}

func (q *Queries) GetSubscriptions(ctx context.Context, userID string) ([]GetSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, getSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsRow
	for rows.Next() {
		var i GetSubscriptionsRow
		if err := rows.Scan(&i.Owner, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionExists = `-- name: SubscriptionExists :one
SELECT EXISTS (
    SELECT 1 FROM subscriptions
    WHERE user_id = $1 AND owner = $2 AND repo = $3
)
`

type SubscriptionExistsParams struct {
	UserID string
	Owner  string
	Repo   string
}

func (q *Queries) SubscriptionExists(ctx context.Context, arg SubscriptionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, subscriptionExists, arg.UserID, arg.Owner, arg.Repo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
