services:
  collector:
    build:
      context: ./services/collector
      dockerfile: Dockerfile
    container_name: github-collector
    ports:
      - "50051:50051"
    networks:
      - hw2-network
    restart: unless-stopped

  processor:
    build:
      context: ./services/processor
      dockerfile: Dockerfile
    container_name: github-processor
    ports:
      - "50053:50053"
    environment:
      - COLLECTOR_ADDR=collector:50051
    depends_on:
      - collector
    networks:
      - hw2-network
    restart: unless-stopped
  
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: github-gateway
    ports:
      - "8080:8080"
    environment:
      - COLLECTOR_ADDR=collector:50051
    depends_on:
      - collector
    networks:
      - hw2-network
    restart: unless-stopped

networks:
  hw2-network:
    driver: bridge