FROM golang:1.26.2-alpine AS builder

WORKDIR /app

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o subscribe ./cmd/subscribe

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /go/bin/migrate /usr/local/bin/migrate

WORKDIR /root/

COPY --from=builder /app/subscribe .
COPY --from=builder /app/migrations ./migrations

EXPOSE 50053

CMD ["sh", "-c", "migrate -path ./migrations -database $DATABASE_URL up && ./subscribe"]